name: Continous Integration
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  run_linters:
    name: Check tgUI
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup cache
        uses: actions/cache@v2
      - name: Install Tools
        run: |
          pip3 install setuptools
          bash tools/ci/install_node.sh
      - name: Run Linters
        run: |
          tgui/bin/tgui --lint
